// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjk7MvlxtlJaIIfJAOKlQkEenE4N_FsM4',
    appId: '1:229182057213:android:610e5ae8e756408d9c6c94',
    messagingSenderId: '229182057213',
    projectId: 'flutter-video-audio-chat-c0bba',
    storageBucket: 'flutter-video-audio-chat-c0bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenVO37lKav35DX6Ho0X6mcaDpSpAKtbA',
    appId: '1:229182057213:ios:2494fd847930ecec9c6c94',
    messagingSenderId: '229182057213',
    projectId: 'flutter-video-audio-chat-c0bba',
    storageBucket: 'flutter-video-audio-chat-c0bba.appspot.com',
    androidClientId: '229182057213-769de8bsmb6hie4cah0p82ld12pfr5ps.apps.googleusercontent.com',
    iosClientId: '229182057213-tidr1bfk2892nof7qko6dt4s1ijqgdsj.apps.googleusercontent.com',
    iosBundleId: 'com.rabbi.chatty',
  );
}
